# Generated by Django 4.2.14 on 2024-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_category_alter_contact_options_contact_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
